name: background_location_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3
  location: ^4.3.0
  path: ^1.8.0
  path_provider: ^2.0.9
  sqflite: ^2.0.2+1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
